[package]
name = "javalang"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]

[dependencies.nom]
features = ["default"]
version = "8.0.0"

[dev-dependencies.anyhow]
version = "1.0.95"